-- 为 pet_config 表添加专注模式相关的配置字段
ALTER TABLE pet_config 
ADD COLUMN IF NOT EXISTS focus_mode_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS focus_mode_show_learn BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_practice BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_test BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_wrong BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_notebook BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_python BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_apps BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_pet BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_exchange BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_leaderboard BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_profile BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_show_security BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS focus_mode_quick_access TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS focus_mode_classes TEXT DEFAULT NULL;
